#!/usr/bin/env python3
"""Build crawlable school/council HTML from local open data; Python stdlib only.

No network requests or writes to data/. Missing optional datasets are expected;
malformed JSON and missing council registers fail the build. Generated directories
are replaced after a successful render, removing stale/closed school URLs.
"""
import argparse
from collections import Counter, defaultdict
from datetime import date
from html import escape
from html.parser import HTMLParser
import json
import math
from pathlib import Path
import re
import shutil
import tempfile
import time
import unicodedata
from urllib.parse import urlencode, urljoin, urlsplit
import xml.etree.ElementTree as ET

BASE = "https://www.schoolsinreach.com"
CROSSLINKS_PATH = Path(__file__).with_name("crosslinks.json")
LABS_FOOTER = '<p class="labs-links">More from Hammant Labs: <a href="https://www.termminder.com/">TermMinder</a> (school term dates) · <a href="https://www.binminder.co.uk/">BinMinder</a> (bin collection reminders) · <a href="https://hammantlabs.com/">Hammant Labs</a></p>'

NATIONS = ("England", "Scotland", "Wales", "Northern Ireland")
SITEMAP_LIMIT = 45_000
NS = "http://www.sitemaps.org/schemas/sitemap/0.9"
RESULTS = {
    "ks2_rwm_exp": "KS2: expected standard in reading, writing & maths (%)",
    "ks2_rwm_high": "KS2: higher standard in reading, writing & maths (%)",
    "ks2_cohort": "KS2 pupils",
    "ks4_p8": "Progress 8",
    "ks4_a8": "Attainment 8",
    "ks4_em5": "GCSE grade 5+ in English & maths (%)",
    "ks4_cohort": "KS4 pupils",
    "ks5_alevel_aps": "A level average point score per entry",
    "ks5_alevel_grade": "A level average grade per entry",
    "ks5_alevel_cohort": "A level students",
}
CSS = """/* Generated by pipeline/seo/build_pages.py; shared static-page styles. */
:root{color-scheme:light;--surface-0:#f4f3f0;--surface-1:#fcfcfb;--surface-2:#f0efec;--border:#dddcd7;--text-primary:#0b0b0b;--text-secondary:#52514e;--accent:#2a78d6}
@media(prefers-color-scheme:dark){:root{color-scheme:dark;--surface-0:#111110;--surface-1:#1a1a19;--surface-2:#262624;--border:#383835;--text-primary:#fff;--text-secondary:#c3c2b7;--accent:#3987e5}}
*{box-sizing:border-box}body{margin:0;background:var(--surface-0);color:var(--text-primary);font:16px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",sans-serif;overflow-wrap:anywhere}a{color:var(--accent)}a:focus-visible{outline:3px solid var(--accent);outline-offset:3px}.topbar{display:flex;align-items:center;gap:16px;padding:8px 16px;min-height:56px;background:var(--surface-1);border-bottom:1px solid var(--border);flex-wrap:wrap}.brand{display:flex;align-items:center;gap:8px;color:var(--text-primary);text-decoration:none;font-weight:700;font-size:17px}.logo{width:22px;height:22px;color:var(--accent);flex:none}.toplinks{margin-left:auto;font-size:13px;display:flex;gap:12px;flex-wrap:wrap}main{max-width:960px;margin:auto;padding:24px 20px 56px}h1{font-size:clamp(1.6rem,4vw,2.2rem);line-height:1.2;margin:16px 0}h2{font-size:1.35rem;margin-top:32px}h3{font-size:1.1rem}.breadcrumb,.note,footer{font-size:14px;color:var(--text-secondary)}.lead{font-size:18px}.cta{display:inline-block;padding:12px 18px;background:var(--accent);color:white;border-radius:8px;text-decoration:none;font-weight:650;margin:8px 0}table{width:100%;border-collapse:collapse;font-size:14px;table-layout:fixed}th,td{padding:9px 7px;border-bottom:1px solid var(--border);text-align:left;vertical-align:top}th{color:var(--text-secondary)}caption{text-align:left;font-weight:600;margin:8px 0}.distance{display:block}.schools th:first-child{width:42%}.nearby{columns:2;padding-left:22px}.nearby li{break-inside:avoid;margin:6px 0}footer{border-top:1px solid var(--border);margin-top:32px;padding-top:16px}.labs-links{font-size:13px}footer li{margin:8px 0}footer ul{padding-left:20px}.admissions th:nth-child(2){width:34%}
@media(max-width:600px){table.responsive,table.responsive tbody{display:block;width:100%}main{padding:16px 14px 40px}.toplinks{margin-left:0}.nearby{columns:1}table.responsive thead{position:absolute;width:1px;height:1px;overflow:hidden;clip-path:inset(50%)}table.responsive tr{display:block;padding:10px 0;border-bottom:1px solid var(--border)}table.responsive td{display:grid;grid-template-columns:minmax(0,42%) minmax(0,58%);padding:4px 0;border:0;gap:8px}table.responsive td::before{content:attr(data-label);font-weight:600;color:var(--text-secondary)}table.responsive td>*{min-width:0}table.responsive td{grid-template-columns:minmax(0,40%) minmax(0,calc(60% - 8px))}}
"""


def esc(value):
    return escape(str(value), quote=True)


def slug(value):
    text = unicodedata.normalize("NFKD", str(value).replace("&", " and "))
    text = text.encode("ascii", "ignore").decode().lower()
    return re.sub(r"[^a-z0-9]+", "-", text).strip("-")[:80].rstrip("-") or "school"


def shorten(text, limit):
    if len(text) <= limit:
        return text
    prefix = text[:limit - 1].rsplit(" ", 1)[0]
    # A single overlong token cannot be shortened without splitting it.
    if " " not in text[:limit - 1]:
        return "…"
    return prefix.rstrip(" ,;:–—-") + "…"


def school_title(name):
    title = f"{name} admissions, catchment & Ofsted | Schools in Reach"
    if len(title) > 70:
        title = title.removesuffix(" | Schools in Reach")
    return shorten(title, 70)


def safe_url(value):
    if not isinstance(value, str):
        return ""
    parsed = urlsplit(value)
    return value if parsed.scheme in ("http", "https") and parsed.netloc else ""


def number(value):
    return isinstance(value, (float, int)) and not isinstance(value, bool) and math.isfinite(value)


def present(value):
    return value is not None and value != "" and value not in ("SUPP", "NE", "NP", "NA", "N/A", "null")


def fmt(value):
    if not present(value):
        return "Not published"
    return f"{value:,}" if number(value) else str(value)


def read_json(path, required=False):
    if not path.exists() and not required:
        return {}
    with path.open(encoding="utf-8") as stream:
        return json.load(stream)



def load_crosslinks(path):
    """Read optional editorial links once per build; bad exports never block pages."""
    try:
        doc = read_json(Path(path))
        tm = doc["termminder"]
        base = tm["base"]
        if base != "https://www.termminder.com":
            return {}
        links = {}
        for group, prefix in (("schools", "/uk/schools/"), ("councils", "/uk/term-dates/")):
            mappings = tm[group]
            if not isinstance(mappings, dict):
                return {}
            if any(not isinstance(value, str) or not re.fullmatch(re.escape(prefix) + r"[A-Za-z0-9_-]+/", value)
                   for value in mappings.values()):
                return {}
            links[group] = {key: base + value for key, value in mappings.items()}
        return links
    except (OSError, ValueError, KeyError, TypeError):
        return {}


def data_date(*documents):
    dates = []
    for doc in documents:
        for key in ("generated", "data_as_at"):
            value = doc.get(key)
            values = value.values() if isinstance(value, dict) else [value]
            for item in values:
                if isinstance(item, str):
                    try:
                        dates.append(date.fromisoformat(item[:10]).isoformat())
                    except ValueError:
                        pass
    return max(dates, default="")


def phase(s):
    raw = str(s.get("phase") or "").lower()
    kind = str(s.get("type") or "").lower()
    group = str(s.get("type_group") or "").lower()
    if "special" in kind + group or "pupil referral" in kind or "alternative provision" in kind:
        return "Special and alternative provision"
    if "middle" in raw:
        return "Middle"
    for word, label in (("nursery", "Nursery"), ("primary", "Primary"), ("secondary", "Secondary"), ("all-through", "All-through"), ("all through", "All-through"), ("16", "Sixth form / 16+")):
        if word in raw:
            return label
    low, high = s.get("age_low"), s.get("age_high")
    if "college" in group or (number(low) and low >= 16):
        return "Sixth form / 16+"
    if number(high) and high <= 11:
        return "Primary"
    if number(low) and low >= 10:
        return "Secondary"
    if number(high) and high >= 16:
        return "All-through"
    return "Other"


def closed(*records):
    return any(r.get("open") is False or any("closed" in str(r.get(k, "")).lower() for k in ("status", "school_status", "establishment_status")) for r in records)


def admissions_records(doc):
    result = {}
    for key in ("primary", "secondary", "schools"):
        result.update(doc.get(key) or {})
    return result


# Mirrors OPEN_BAND_MILES in site/js/admissions.js: a published "cut-off" beyond this
# (e.g. 7.2 or 350 mi) means everyone in that band was offered, not a real boundary.
OPEN_BAND_MILES = 3


def year_distances(y):
    value = y.get("max_distance")
    return value if isinstance(value, dict) else {"All": value}


def is_open_band(value):
    return number(value) and value > OPEN_BAND_MILES


def all_offered(y):
    value = y.get("all_offered")
    if isinstance(value, list):
        return value
    return (y.get("groups") or list(year_distances(y))) if value else []


def has_admissions(rec):
    return any(any(number(y.get(k)) for k in ("pan", "applications", "total_offers"))
               or any(number(v) for v in year_distances(y).values()) or bool(all_offered(y))
               for y in rec.get("years", {}).values())


OFSTED_GRADES = ("Outstanding", "Good", "Requires improvement", "Inadequate")
# Ofsted report cards (from November 2025) grade each area on this scale, with no overall grade.
REPORT_CARD_GRADES = ("Exceptional", "Strong standard", "Expected standard", "Needs attention", "Urgent improvement")


def uk_date(value):
    """2025-01-22 -> 22 January 2025; anything unparseable is returned unchanged."""
    try:
        d = date.fromisoformat(str(value)[:10])
    except (TypeError, ValueError):
        return value
    return f"{d.day} {d.strftime('%B %Y')}"


def area_summary(facts, grades=OFSTED_GRADES, fallback="Area judgements published", prefix=""):
    """One line for inspections that grade each area but give no overall judgement."""
    counts = Counter(v for _, v in facts if v in grades)
    if not counts:
        return fallback
    if len(counts) == 1:
        grade, n = counts.popitem()
        return prefix + (f"{grade} in all {n} graded areas" if n > 1 else f"{grade} in its graded area")
    parts = [f"{g} in {counts[g]} area{'s' if counts[g] > 1 else ''}" for g in grades if counts[g]]
    return prefix + ", ".join(parts)


def ofsted_facts(rec):
    latest = rec.get("latest") or {}
    facts = []
    if latest.get("kind") == "report_card":
        facts = [(k.replace("_", " ").capitalize(), fmt(v)) for k, v in latest.get("report_card", {}).items() if present(v) and v != "Not applicable"]
        summary = area_summary(facts, REPORT_CARD_GRADES, "Report card", "Report card: ") if facts else ""
        return summary, uk_date(latest.get("date")), facts
    judgments = latest.get("judgements") or {}
    overall = judgments.get("overall_effectiveness") or latest.get("overall_effectiveness")
    if latest.get("kind") == "ungraded":
        overall = latest.get("outcome")
        prior = rec.get("last_graded") or rec.get("previous") or {}
        grade = (prior.get("judgements") or {}).get("overall_effectiveness") or prior.get("overall_effectiveness")
        if grade and grade != "Not judged":
            facts.append(("Last graded overall judgement", f"{grade} ({uk_date(prior.get('date')) or 'date not published'})"))
    for key, value in judgments.items():
        if present(value) and value not in ("Not judged", "Not applicable"):
            facts.append((key.replace("_", " ").capitalize(), ("Yes" if value else "No") if isinstance(value, bool) else str(value)))
    if overall == "Not judged":
        overall = None
    return overall or (area_summary(facts) if facts else ""), uk_date(latest.get("date")), facts


def result_rows(row):
    return [(label, fmt(row[key]), row.get(key + "_year") or row.get(key[:3] + "_year") or "Year not published")
            for key, label in RESULTS.items() if present(row.get(key))]


def pupil_rows(s, census, characteristics, char_doc):
    rows = []
    if number(characteristics.get("headcount")):
        pupils = characteristics["headcount"]
        rows.append(("Pupils", fmt(pupils), char_doc.get("time_period") or "Latest census"))
    elif number(census.get("pupils")):
        pupils = census["pupils"]
        rows.append(("Pupils", fmt(pupils), census.get("year") or census.get("census_date") or "Latest census"))
    else:
        pupils = s.get("pupils")
        if number(pupils):
            rows.append(("Pupils", fmt(pupils), s.get("census_date") or "Published school roll"))
    for label, char_value, key in (
        ("Eligible for free school meals", (characteristics.get("fsm") or {}).get("eligible_pct"), "fsm_pct"),
        ("English as an additional language", (characteristics.get("language") or {}).get("eal_pct"), "eal_pct"),
        ("SEN support", None, "sen_support_pct"),
        ("Education, health and care (EHC) plan", None, "ehcp_pct"),
    ):
        value = char_value if number(char_value) else census.get(key)
        vintage = char_doc.get("time_period") if number(char_value) else census.get("year")
        if key == "fsm_pct" and not number(char_value):
            vintage = census.get("fsm_pct_source") or vintage
        if number(value):
            rows.append((label, f"{value:g}%", vintage or "Year not published"))
    return pupils, rows


def table(headers, rows, caption="", css=""):
    if not rows:
        return ""
    return (f'<table class="responsive {esc(css)}">' + (f"<caption>{esc(caption)}</caption>" if caption else "")
            + "<thead><tr>" + "".join(f'<th scope="col">{esc(h)}</th>' for h in headers) + "</tr></thead><tbody>"
            + "".join("<tr>" + "".join(f'<td data-label="{esc(h)}"><div>{v}</div></td>' for h, v in zip(headers, row)) + "</tr>" for row in rows) + "</tbody></table>")


def distance_text(y):
    distances = year_distances(y)
    groups = list(dict.fromkeys((y.get("groups") or []) + list(distances) + all_offered(y)))
    parts = []
    for group in groups:
        value = distances.get(group)
        text = f"{value:.2f} mi" if number(value) and not is_open_band(value) else ""
        if group in all_offered(y) or is_open_band(value):
            text = (text + "; " if text else "") + "All offered"
        if text:
            parts.append((f"{group}: " if group != "All" else "") + text)
    return parts


def latest_distance(rec):
    years = rec.get("years") or {}
    if not years:
        return ""
    year = max(years)
    parts = distance_text(years[year])
    return f"{year}: " + "; ".join(parts) if parts else ""


def admissions_html(rec, council, doc, school):
    name, nation = council["name"], council["nation"]
    html = "<h2>Admissions</h2>"
    if not has_admissions(rec):
        if any(has_admissions(r) for r in admissions_records(doc).values()):
            text = f"Admissions figures for this school aren't loaded yet. {name} has figures for some other schools; a missing record does not establish whether this school had spare places."
        else:
            text = f"{name} council's admissions figures aren't loaded yet."
        html += f"<p>{esc(text)}</p>"
        if "independent" in str(school.get("type_group", school.get("type", ""))).lower():
            html += "<p>This is an independent school. It sets its own admissions process, including any assessments, interviews and fees; contact the school directly.</p>"
    else:
        rows = []
        for year, y in sorted(rec["years"].items(), reverse=True):
            distances = distance_text(y)
            cells = "".join(f'<span class="distance">{esc(t)}</span>' for t in distances) or "Not published"
            rows.append([esc(year), cells, esc(fmt(y.get("pan"))), esc(fmt(y.get("applications"))), esc(fmt(y.get("total_offers")))])
        html += table(["Entry year", "Last distance offered", "Places (PAN)", "Applications", "Offers"], rows, "Published admissions history", "admissions")
        year = max(rec["years"])
        y = rec["years"][year]
        finite = [(g, v) for g, v in year_distances(y).items() if number(v) and not is_open_band(v)]
        if len(finite) == 1:
            group, value = finite[0]
            band = f" in band {group}" if group != "All" else ""
            html += f"<p>{esc(f'In {year} the last place offered on distance{band} went to a child living {value:.2f} miles away.')}</p>"
        elif finite:
            low, high = min(v for _, v in finite), max(v for _, v in finite)
            html += f"<p>{esc(f'In {year} the last distances offered ranged from {low:.2f} to {high:.2f} miles across the published bands or admission groups.')}</p>"
        if all_offered(y):
            html += "<p>“All offered” means the published group had places for all eligible applicants; its distance is not a cut-off for admission.</p>"
        html += '<p class="note">Distances are in miles (mi), as in the map app. PAN is the published admission number. Bands and admission groups have separate criteria; school-wide places, applications and offers are not counts for each band. Past offers are a guide, not a promise of a place.</p>'
        if doc.get("distance_notes"):
            html += f'<p class="note">{esc(doc["distance_notes"])}</p>'
        # Preserve school-specific exceptions (nodal points, faith or selective queues).
        notes = y.get("notes") or []
        if isinstance(notes, str):
            notes = [notes]
        if notes:
            html += '<p class="note">' + esc(" ".join(notes)) + "</p>"
    if nation in ("Scotland", "Wales"):
        html += f"<p>{esc(nation)} uses catchment areas and other admission priorities. A nearby address alone does not establish eligibility; check the council’s catchment boundary and school criteria.</p>"
    elif nation == "Northern Ireland":
        html += "<p>Northern Ireland’s post-primary admissions are not distance-based. Schools use their published criteria, and some grammar schools use entrance assessments. We do not provide chance estimates here.</p>"
    url = next((safe_url(obj.get(k)) for obj in (council, doc) for k in ("admissions_url", "admissions_page", "url") if safe_url(obj.get(k))), "")
    if not url:
        url = next((safe_url(s.get("url")) for s in doc.get("sources", []) if re.search(r"admission|allocation|offer", str(s.get("title", "")), re.I) and safe_url(s.get("url"))), "")
    if url:
        html += f'<p><a href="{esc(url)}">{esc(name)} admissions information and published allocations</a></p>'
    return html


class HeadMetadata(HTMLParser):
    def __init__(self, text):
        super().__init__()
        self.adsense = ""
        self.image = ""
        self.feed(text)

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if tag == "meta" and a.get("name") == "google-adsense-account":
            self.adsense = a.get("content", "")
        if tag == "meta" and a.get("property") == "og:image":
            self.image = safe_url(urljoin(BASE, a.get("content", "")))


def breadcrumbs(items):
    return {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [
        {"@type": "ListItem", "position": i, "name": name, "item": BASE + path}
        for i, (name, path) in enumerate(items, 1)]}


def document(title, description, path, body, crumbs, metadata, structured=None, indexable=True):
    schemas = [breadcrumbs(crumbs)] + ([structured] if structured else [])
    # HTML entities must not be used inside JSON. Escape '<' instead, preventing </script> injection.
    ld = json.dumps(schemas, ensure_ascii=False, separators=(",", ":")).replace("<", "\\u003c").replace("&", "\\u0026")
    head = f'<title>{esc(title)}</title>\n<meta name="description" content="{esc(description)}">\n<link rel="canonical" href="{esc(BASE + path)}">'
    if metadata.adsense:
        head += f'\n<meta name="google-adsense-account" content="{esc(metadata.adsense)}">'
    if not indexable:
        head += '\n<meta name="robots" content="noindex,follow">'
    for key, value in (("og:type", "website"), ("og:site_name", "Schools in Reach"), ("og:title", title), ("og:description", description), ("og:url", BASE + path)):
        head += f'\n<meta property="{key}" content="{esc(value)}">'
    for key, value in (("twitter:card", "summary"), ("twitter:title", title), ("twitter:description", description)):
        head += f'\n<meta name="{key}" content="{esc(value)}">'
    if metadata.image:
        head += f'\n<meta property="og:image" content="{esc(metadata.image)}"><meta name="twitter:image" content="{esc(metadata.image)}">'
    trail = ' <span aria-hidden="true">›</span> '.join(f'<a href="{esc(url)}">{esc(name)}</a>' if i < len(crumbs) - 1 else f'<span aria-current="page">{esc(name)}</span>' for i, (name, url) in enumerate(crumbs))
    return f'''<!doctype html>
<html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
{head}
<link rel="stylesheet" href="/css/seo.css"><script type="application/ld+json">{ld}</script>
</head><body><header class="topbar"><a class="brand" href="/"><svg class="logo" viewBox="0 0 100 100" aria-hidden="true"><circle cx="50" cy="50" r="42" fill="none" stroke="currentColor" stroke-width="10"/><circle cx="50" cy="50" r="14" fill="currentColor"/></svg><span>Schools in Reach</span></a><nav class="toplinks" aria-label="Main"><a href="/council/">Browse councils</a><a href="/apply.html">How to apply</a><a href="/faq.html">Questions</a><a href="/about.html">About &amp; data</a><a href="/agents/">For estate agents</a></nav></header>
<main><nav class="breadcrumb" aria-label="Breadcrumb">{trail}</nav>{body}</main><script type="module" src="/js/page-analytics.js"></script></body></html>
'''


def sources_footer(documents, updated):
    sources = {}
    for doc in documents:
        for source in doc.get("sources", []):
            key = (source.get("title", "Source"), source.get("url", ""), source.get("licence", ""))
            sources[key] = source
    items = []
    for title, url, licence in sources:
        link = f'<a href="{esc(url)}">{esc(title)}</a>' if safe_url(url) else esc(title)
        items.append(f"<li>{link}" + (f" — {esc(licence)}" if licence else " — see publisher for licence terms") + "</li>")
    return '<footer><h2>Sources and data dates</h2>' + (f"<p>Data updated: {esc(updated)}. Individual inspection, results and census dates are shown above where published.</p>" if updated else "") + "<ul>" + "".join(items) + '</ul><p>Contains public sector information licensed under the <a href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/">Open Government Licence v3.0</a> where indicated above.</p><p><a href="/agents/">For estate agents</a></p>' + LABS_FOOTER + '</footer>'


def school_path(s):
    urn = str(s["urn"])
    if not re.fullmatch(r"[0-9]+", urn):
        raise ValueError(f"Invalid school identifier: {urn!r}")
    return f'/school/{urn}-{slug(s["name"])}/'


def coordinates(s):
    lat, lon = s.get("lat"), s.get("lon")
    if number(lat) and number(lon) and -90 <= lat <= 90 and -180 <= lon <= 180:
        return lat, lon
    return None


def proximity(a, b):
    pa, pb = coordinates(a), coordinates(b)
    if not pa or not pb:
        return math.inf
    lat1, lon1, lat2, lon2 = map(math.radians, (*pa, *pb))
    return math.sin((lat2 - lat1) / 2) ** 2 + math.cos(lat1) * math.cos(lat2) * math.sin((lon2 - lon1) / 2) ** 2


def render_school(item, council, peers, metadata, crosslinks=None):
    s, rec, doc = item["school"], item["admissions"], item["admissions_doc"]
    name, path = s["name"], item["path"]
    cpath = council["path"]
    group = phase(s)
    place = ", ".join(str(x) for x in (s.get("town") or s.get("locality"), str(s.get("postcode") or "").split(" ")[0]) if x)
    kind = s.get("type") or f"{group.lower()} school"
    phase_label = {"Other": "school", "Nursery": "nursery school", "Sixth form / 16+": "sixth form or college", "Special and alternative provision": "special or alternative provision school"}.get(group, group.lower() + " school")
    article = "an" if phase_label[0].lower() in "aeiou" else "a"
    opening = f"{name} is {article} {phase_label}"
    if s.get("type"):
        opening += f" ({kind})"
    if number(s.get("age_low")) and number(s.get("age_high")):
        opening += f", ages {s['age_low']}–{s['age_high']}"
    opening += f", in {place}" if place else ""
    # Academy trusts and independent schools are not run by the council.
    maintained = council["nation"] != "Northern Ireland" and ("local authority" in kind.lower() or kind.lower() in ("community school", "voluntary controlled school"))
    opening += f", run by {council['name']} council." if maintained else f", in the {council['name']} council area."
    if number(item["pupils"]):
        opening += f" It has {fmt(item['pupils'])} pupils in the published census."
    headline, inspection_date, findings = item["ofsted"]
    if headline:
        opening += " Latest Ofsted inspection" + (f" ({inspection_date})" if inspection_date else "") + f": {headline}."
    policy = s.get("admissions_policy") or ""
    if s.get("selective") is True or (re.search(r"selective", policy, re.I) and not re.search(r"non.selective", policy, re.I)):
        opening += " It is listed as selective (grammar); check its entrance assessment requirements." if council["nation"] == "Northern Ireland" else " It is listed as selective; check the school’s grammar / 11+ entrance requirements."
    elif s.get("selective") is False or re.search(r"non.selective", policy, re.I):
        opening += " It is listed as non-selective."
    body = f'<h1>{esc(name)}</h1><p class="lead">{esc(opening)}</p>'
    if council["nation"] == "Scotland":
        body += '<p class="note">The age range is derived from the school’s published departments. Pupil rolls exclude nursery/early learning children. Inspections are by Education Scotland, not Ofsted.</p>'
    elif council["nation"] == "Wales":
        body += '<p class="note">Welsh schools are inspected by Estyn, not Ofsted. England’s Progress 8 and Attainment 8 measures do not apply here.</p>'
    elif council["nation"] == "Northern Ireland":
        body += '<p class="note">School inspections are by the Education and Training Inspectorate, not Ofsted.</p>'
    cta = "Check your chances from your postcode" if item["has_admissions"] else "See this school on the map"
    route = "/#" + urlencode({"school": s["urn"], "la": council["la_code"], "tab": "admissions"})
    body += f'<p><a class="cta" href="{esc(route)}">{cta}</a></p>'
    body += admissions_html(rec, council, doc, s)
    if headline or findings:
        body += "<h2>Ofsted</h2>"
        body += f"<p>{esc(headline or 'Published judgements')}" + (f" — inspected {esc(inspection_date)}" if inspection_date else "") + ".</p>"
        body += table(["Area", "Judgement"], [[esc(k), esc(v)] for k, v in findings])
        report_url = safe_url(item["ofsted_rec"].get("report_url"))
        if report_url:
            body += f'<p><a href="{esc(report_url)}">Read the Ofsted inspection report</a></p>'
    term_url = (crosslinks or {}).get("schools", {}).get(str(s["urn"]))
    if term_url:
        body += f'<section aria-labelledby="term-dates"><h2 id="term-dates">Term dates</h2><p>This school’s term and holiday dates, INSET days where known, and a calendar you can subscribe to, on <a href="{esc(term_url)}">TermMinder</a>.</p></section>'
    if item["results"]:
        body += "<h2>Results</h2>" + table(["Measure", "Result", "Academic year"], [[esc(v) for v in row] for row in item["results"]])
        if present(item["league_row"].get("ks4_p8")):
            body += '<p class="note">Progress 8 compares progress with pupils who had similar primary results; 0 is the national average. Its publication year can differ from the other GCSE results above.</p>'
    if item["pupil_rows"]:
        body += "<h2>Pupils</h2>" + table(["Measure", "Pupils / percentage", "Data period"], [[esc(v) for v in row] for row in item["pupil_rows"]])
    nearby = [p for p in peers if p["path"] != path and phase(p["school"]) == group]
    nearby.sort(key=lambda p: (proximity(s, p["school"]), p["school"]["name"].casefold()))
    if nearby:
        body += '<h2>Nearby schools</h2><p class="note">Other schools in the same council and phase. Ordered by distance where coordinates are available, then by name; locations may be postcode centres.</p><ul class="nearby">'
        body += "".join(f'<li><a href="{esc(p["path"])}">{esc(p["school"]["name"])}</a></li>' for p in nearby[:8]) + "</ul>"
    body += sources_footer(item["documents"], item["date"])
    address = {"@type": "PostalAddress", "addressCountry": "GB"}
    for key, value in (("streetAddress", s.get("street")), ("addressLocality", s.get("town") or s.get("locality")), ("postalCode", s.get("postcode")), ("addressRegion", council["name"])):
        if value:
            address[key] = value
    schema = {"@context": "https://schema.org", "@type": {"Primary": "ElementarySchool", "Middle": "MiddleSchool", "Secondary": "HighSchool"}.get(group, "School"), "name": name, "url": BASE + path, "address": address}
    if coordinates(s):
        schema["geo"] = {"@type": "GeoCoordinates", "latitude": s["lat"], "longitude": s["lon"]}
    facts = [f"{shorten(name, 85)} in {council['name']} ({s.get('postcode') or council['nation']})."]
    last = latest_distance(rec)
    if last:
        facts.append(f"Last offers {last}.")
    elif headline:
        facts.append(f"Ofsted: {headline}.")
    elif number(item["pupils"]):
        facts.append(f"{fmt(item['pupils'])} pupils.")
    facts.append(f"Explore {group.lower()} admissions, catchment information, published school facts and nearby schools on Schools in Reach.")
    description = shorten(" ".join(facts), 160)
    return document(school_title(name), description, path, body, [("Home", "/"), (council["name"], cpath), (name, path)], metadata, schema, item["indexable"])


def render_council(council, items, docs, metadata, crosslinks=None):
    name, nation, path = council["name"], council["nation"], council["path"]
    loaded = sum(i["has_admissions"] for i in items)
    cutoffs = sum(any(number(v) for y in i["admissions"].get("years", {}).values() for v in year_distances(y).values()) for i in items)
    body = f'<h1>{esc(name)} school admissions: last distances offered, Ofsted and results</h1><p class="lead">Browse {len(items):,} open schools in {esc(name)}, {esc(nation)}.'
    body += f" Admissions figures are loaded for {loaded:,} schools; distance cut-offs are available for {cutoffs:,}." if loaded else " Admissions cut-off figures are not loaded yet."
    body += "</p>"
    term_url = (crosslinks or {}).get("councils", {}).get(str(council["la_code"]))
    if term_url:
        body += f'<p><a href="{esc(term_url)}">School term dates in {esc(name)}: holidays, half terms and INSET days on TermMinder.</a></p>'
    if nation == "England":
        body += '<p>Secondary applications close on <strong>31 October</strong>; primary applications close on <strong>15 January</strong>. Apply through your home council, even when choosing a school across a council boundary. <a href="/apply.html">How to apply for a school place</a>.</p>'
    elif nation in ("Scotland", "Wales"):
        body += f"<p>{esc(nation)} uses catchment areas and other admission priorities rather than the distance cut-offs used in much of England. Check the council’s catchment boundaries and application timetable. {'Education Scotland' if nation == 'Scotland' else 'Estyn'} inspects schools here; Ofsted applies to England.</p>"
    else:
        body += '<p>Northern Ireland’s post-primary admissions are not distance-based. Check the Education Authority’s timetable and each school’s published criteria, including entrance assessments for participating grammar schools. No chance estimates are available here. Inspections are by the Education and Training Inspectorate.</p>'
    groups = defaultdict(list)
    for item in items:
        groups[phase(item["school"])].append(item)
    for group in sorted(groups, key=lambda g: ({"Secondary": 0, "Primary": 1}.get(g, 2), g)):
        headers = ["School", "Ofsted", "Last distance offered", "Pupils"] if nation == "England" else ["School", "Pupils"]
        rows = []
        for item in sorted(groups[group], key=lambda i: i["school"]["name"].casefold()):
            cells = [f'<a href="{esc(item["path"])}">{esc(item["school"]["name"])}</a>']
            if nation == "England":
                cells += [esc(item["ofsted"][0] or "Not loaded"), esc(latest_distance(item["admissions"]) or "Not published")]
            cells += [esc(fmt(item["pupils"]))]
            rows.append(cells)
        body += f"<h2>{esc(group)}</h2>" + table(headers, rows, css="schools")
    body += '<p><a href="/council/">Browse all councils</a></p>' + sources_footer(docs, data_date(*docs))
    description = shorten(f"Explore {len(items):,} schools in {name}, {nation}: admissions, catchment information, available inspection reports, results and pupil numbers. Browse schools by phase.", 160)
    return document(f"{name} school admissions & catchments | Schools in Reach", description, path, body, [("Home", "/"), ("Councils", "/council/"), (name, path)], metadata)


def write_sitemap(path, entries, index=False):
    ET.register_namespace("", NS)
    root = ET.Element(f"{{{NS}}}" + ("sitemapindex" if index else "urlset"))
    for url, modified in entries:
        node = ET.SubElement(root, f"{{{NS}}}" + ("sitemap" if index else "url"))
        ET.SubElement(node, f"{{{NS}}}loc").text = BASE + url
        if modified:
            ET.SubElement(node, f"{{{NS}}}lastmod").text = modified
    path.parent.mkdir(parents=True, exist_ok=True)
    ET.ElementTree(root).write(path, encoding="utf-8", xml_declaration=True)


def build(site, sitemap_limit=SITEMAP_LIMIT, crosslinks_path=None):
    started = time.perf_counter()
    site = Path(site).resolve()
    if not 1 <= sitemap_limit <= SITEMAP_LIMIT:
        raise ValueError("School sitemap limit must be between 1 and 45,000")
    crosslinks = load_crosslinks(CROSSLINKS_PATH if crosslinks_path is None else crosslinks_path)
    data = site / "data"
    indices = [read_json(data / "england/las.json", required=True)]
    indices += [read_json(p) for p in sorted((data / "uk").glob("*_las.json"))]
    councils = []
    paths, codes = set(), set()
    for index in indices:
        for entry in index.get("las", []):
            c = dict(entry)
            c["nation"] = c.get("nation") or (c.get("region") if c.get("region") in NATIONS else "England")
            c["la_code"] = str(c["la_code"])
            if not re.fullmatch(r"[A-Za-z0-9]+", c["la_code"]) or c["la_code"] in codes:
                raise ValueError(f"Invalid or duplicate council code: {c['la_code']}")
            codes.add(c["la_code"])
            c["path"] = f'/council/{slug(c["name"])}/'
            if c["path"] in paths:
                c["path"] = f'/council/{slug(c["name"])}-{slug(c["nation"])}/'
            if c["path"] in paths:
                raise ValueError("Duplicate council URL")
            paths.add(c["path"])
            councils.append(c)
    if not councils:
        raise ValueError("No councils found in local data")
    metadata = HeadMetadata((site / "index.html").read_text(encoding="utf-8"))
    totals = Counter()
    nations = {nation: Counter() for nation in NATIONS}
    school_urls, page_urls, dates = [], [], []
    seen = set()
    slugs = {}
    # Rendering into a temporary sibling tree keeps a failed run from deleting good output.
    with tempfile.TemporaryDirectory(prefix=".seo-build-", dir=site) as staging:
        stage = Path(staging)
        for folder in ("school", "council", "sitemaps"):
            (stage / folder).mkdir()
        for council in sorted(councils, key=lambda c: (c["nation"], c["name"])):
            directory = data / "la" / council["la_code"]
            register = read_json(directory / "schools.json", required=True)
            adm, ofs, league, chars = [read_json(directory / f"{name}.json") for name in ("admissions", "ofsted", "league_tables", "characteristics")]
            admissions = admissions_records(adm)
            results = {str(r["urn"]): r for r in league.get("rows", [])}
            items = []
            for s in register.get("schools", []):
                urn = str(s["urn"])
                rec, ofsted = admissions.get(urn, {}), ofs.get("schools", {}).get(urn, {})
                if closed(s, rec, ofsted):
                    totals["closed_skipped"] += 1
                    continue
                if urn in seen:
                    raise ValueError(f"School identifier appears in multiple councils: {urn}")
                seen.add(urn)
                path = school_path(s)
                slugs.setdefault(council["la_code"], {})[urn] = slug(s["name"])
                detail = read_json(directory / "schools" / f"{urn}.json")
                characteristic = chars.get("schools", {}).get(urn, {})
                census = detail.get("census") or {}
                pupils, pupil_data = pupil_rows(s, census, characteristic, chars)
                league_row = results.get(urn, {})
                result_data, inspection = result_rows(league_row), ofsted_facts(ofsted)
                has_results = any(present(league_row.get(k)) for k in RESULTS if not k.endswith("cohort"))
                has_adm = has_admissions(rec)
                quality = sum((has_adm, bool(inspection[0] or inspection[2]), has_results, number(pupils)))
                docs = [register] + ([adm] if has_adm else []) + ([ofs] if inspection[0] or inspection[2] else []) + ([league] if result_data else []) + ([detail] if census else []) + ([chars] if characteristic else [])
                updated = data_date(*docs)
                items.append({"school": s, "admissions": rec, "admissions_doc": adm, "has_admissions": has_adm, "ofsted": inspection, "ofsted_rec": ofsted, "league_row": league_row, "results": result_data, "pupils": pupils, "pupil_rows": pupil_data, "documents": docs, "date": updated, "indexable": quality >= 2, "path": path})
            for item in items:
                html = render_school(item, council, items, metadata, crosslinks)
                if len(html.encode("utf-8")) > 26_000:
                    raise ValueError(f"School page exceeds ~25 KB: {item['path']}")
                target = stage / item["path"].lstrip("/") / "index.html"
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(html, encoding="utf-8")
                status = "indexable" if item["indexable"] else "noindexed"
                totals["schools"] += 1
                totals[status] += 1
                nations[council["nation"]]["schools"] += 1
                nations[council["nation"]][status] += 1
                if item["indexable"]:
                    school_urls.append((item["path"], item["date"]))
            docs = [register, adm, ofs, league, chars]
            updated = max([data_date(*docs)] + [i["date"] for i in items])
            dates.append(updated)
            target = stage / council["path"].lstrip("/") / "index.html"
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(render_council(council, items, docs, metadata, crosslinks), encoding="utf-8")
            page_urls.append((council["path"], updated))
        latest = max(dates + [data_date(*indices)])
        body = '<h1>Browse schools by council</h1><p>Find schools across England, Scotland, Wales and Northern Ireland. Council pages explain which admissions and inspection data is available locally.</p>'
        for nation in NATIONS:
            members = sorted((c for c in councils if c["nation"] == nation), key=lambda c: c["name"].casefold())
            if members:
                body += f'<h2>{nation}</h2><ul class="nearby">' + "".join(f'<li><a href="{esc(c["path"])}">{esc(c["name"])}</a></li>' for c in members) + "</ul>"
        body += sources_footer(indices, latest)
        (stage / "council/index.html").write_text(document("UK schools by council | Schools in Reach", "Browse UK schools by council: school admissions, catchments, available Ofsted reports, results and pupil numbers in England, Scotland, Wales and Northern Ireland.", "/council/", body, [("Home", "/"), ("Councils", "/council/")], metadata), encoding="utf-8")
        page_urls += [(p, latest) for p in ("/", "/about.html", "/apply.html", "/faq.html", "/council/", "/agents/")]
        write_sitemap(stage / "sitemaps/pages.xml", page_urls)
        maps = [("/sitemaps/pages.xml", latest)]
        for start in range(0, len(school_urls), sitemap_limit):
            chunk = school_urls[start:start + sitemap_limit]
            path = f"/sitemaps/schools-{start // sitemap_limit + 1}.xml"
            write_sitemap(stage / path.lstrip("/"), chunk)
            maps.append((path, max(d for _, d in chunk)))
        write_sitemap(stage / "sitemap.xml", maps, index=True)
        # One small map per council: the widget only fetches the councils near a listing.
        (stage / "slugs").mkdir()
        for la_code, la_slugs in slugs.items():
            (stage / "slugs" / f"{la_code}.json").write_text(json.dumps(la_slugs, ensure_ascii=True, separators=(",", ":")), encoding="utf-8")
        if (site / "embed").is_symlink() or (site / "embed/slugs").is_symlink():
            raise ValueError("Refusing to replace symlink: embed/slugs")
        totals["bytes"] = sum(p.stat().st_size for p in stage.rglob("*") if p.is_file()) + len(CSS.encode("utf-8"))
        for folder in ("school", "council", "sitemaps"):
            existing = site / folder
            if existing.is_symlink():
                raise ValueError(f"Refusing to replace symlink: {existing}")
            if existing.exists():
                shutil.rmtree(existing)
            shutil.move(str(stage / folder), existing)
        (stage / "sitemap.xml").replace(site / "sitemap.xml")
        (site / "embed").mkdir(exist_ok=True)
        if (site / "embed/slugs").exists():
            shutil.rmtree(site / "embed/slugs")
        shutil.move(str(stage / "slugs"), site / "embed/slugs")
        (site / "embed/slugs.json").unlink(missing_ok=True)
        (site / "css").mkdir(exist_ok=True)
        (site / "css/seo.css").write_text(CSS, encoding="utf-8")
    totals.update({"councils": len(councils), "sitemap_files": len(maps) + 1, "pages": totals["schools"] + len(councils) + 1})
    return {**totals, "nations": nations, "runtime": time.perf_counter() - started}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--site-dir", type=Path, default=Path(__file__).resolve().parents[2] / "site")
    args = parser.parse_args()
    try:
        summary = build(args.site_dir)
    except (OSError, ValueError, KeyError, TypeError) as exc:
        parser.exit(1, f"SEO build failed: {exc}\n")
    print(f"Pages generated: {summary['pages']:,} ({summary['schools']:,} schools, {summary['councils']:,} councils, 1 council directory)")
    print(f"School quality gate: {summary.get('indexable', 0):,} indexable; {summary.get('noindexed', 0):,} noindexed; {summary.get('closed_skipped', 0):,} closed skipped")
    for nation, counts in summary["nations"].items():
        print(f"  {nation}: {counts['schools']:,} schools; {counts['indexable']:,} indexable; {counts['noindexed']:,} noindexed")
    print(f"Sitemap files: {summary['sitemap_files']} (including index)")
    print(f"Total generated bytes: {summary['bytes']:,}; runtime: {summary['runtime']:.2f}s")


if __name__ == "__main__":
    main()
